export const defaultSC40Layout = {
  uid: 'sc4.0.defaultl',
  name: 'SC4.0 Phone',
  width: 375,
  height: 800,
  bindedKbList: 'sc4.0.defaultkb',
  nosleep: true,
  nonav: false,
  cols: 12,
  rowHeight: 4,
  pages: [
    {
      uid: 'b0246549-0273-4519-b902-6700371209b5',
      name: 'Ship',
      pageConfig: {
        bgcolor: '#506173',
        bgimg: 'v1.png',
        bgsize: 'cover',
        bgpos: {
          x: 'center',
          y: 'center'
        },
        bgrepeat: 'no-repeat'
      },
      items: [
        {
          grid: {
            i: 'caab7155-78df-416b-8901-b913f839247f',
            x: 0,
            y: 1,
            w: 8,
            h: 5
          },
          name: 'Flight Ready',
          color: '#ffffff',
          bgcolor: '#28A745',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '759a2dfb-1c93-47ff-8a03-51358b24a1b2',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '22',
          onclickbgcolor: 'rgba(40, 167, 69, 0.59)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'de0e9a2a-fe7b-4db6-9bab-7bf3ac8079d9',
            x: 8,
            y: 1,
            w: 4,
            h: 5
          },
          name: 'Power',
          color: '#ffffff',
          bgcolor: 'rgba(167,97,40,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'b5f9706d-1eef-490f-a342-9a89eb0cd72d',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(167,97,40,0.6)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'c5e2f06d-4a7d-467d-a467-580edeb294e0',
            x: 0,
            y: 6,
            w: 4,
            h: 4
          },
          name: 'Engine',
          color: '#ffffff',
          bgcolor: 'rgba(167,97,40,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '5cf3dbcc-176c-4fbe-b603-d43ff51c59b4',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(167,97,40,0.6)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '1cd8d6d3-5d0d-4492-ac1e-6e1d17c94a38',
            x: 4,
            y: 6,
            w: 4,
            h: 4
          },
          name: 'Shields',
          color: '#ffffff',
          bgcolor: 'rgba(167,97,40,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '558c9d3f-9a65-48bd-aed4-d40ad39d25de',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(167,97,40,0.6)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'f96a639b-0cd5-458d-84f0-8d90f11f615c',
            x: 8,
            y: 6,
            w: 4,
            h: 4
          },
          name: 'Weapons',
          color: '#ffffff',
          bgcolor: 'rgba(167,97,40,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'a0c006d5-b201-46d1-bf42-31ea26d94be9',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(167,97,40,0.6)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'ade49120-f0a6-4503-adcd-b836d9e9bab9',
            x: 0,
            y: 19,
            w: 4,
            h: 4
          },
          name: 'Doors',
          color: '#ffffff',
          bgcolor: 'rgba(40,84,167,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'd8404b75-fe5b-4833-b3c2-b97a1f534c6c',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(40,84,167,0.63)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '24d89c9b-fa04-41b8-a92b-5fcb55d7f6e0',
            x: 4,
            y: 23,
            w: 4,
            h: 4
          },
          name: 'Pads',
          color: '#ffffff',
          bgcolor: 'rgba(40,84,167,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '9e4bbfe5-ff9a-4861-8a0c-dab53cff0113',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(40,84,167,0.63)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '8c18020d-aa6d-4690-b694-1f0ac3d020d0',
            x: 0,
            y: 23,
            w: 4,
            h: 4
          },
          name: 'Ask Land',
          color: '#ffffff',
          bgcolor: 'rgba(40,84,167,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '833ce51c-f7f9-4a8d-b162-198819161776',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(40,84,167,0.63)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'c40a6947-ad62-4d6b-a32b-c1989ce3caaa',
            x: 0,
            y: 10,
            w: 4,
            h: 4
          },
          name: 'VTol',
          color: '#ffffff',
          bgcolor: 'rgba(40,165,167,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '1f5f0f4e-6ea2-4d11-a81e-a73f0e8d93ac',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(40,165,167,0.58)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '7a1493ed-a714-43d0-a9c8-455f9676c89b',
            x: 4,
            y: 10,
            w: 4,
            h: 4
          },
          name: 'Decoupled',
          color: '#ffffff',
          bgcolor: 'rgba(40,165,167,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '792fb2e9-0bed-4d73-b671-09bd45bab358',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(40,165,167,0.58)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '103fde96-9fd2-4d7a-94fc-ac6f899ef58e',
            x: 8,
            y: 10,
            w: 4,
            h: 4
          },
          name: 'Cruise',
          color: '#ffffff',
          bgcolor: 'rgba(40,165,167,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'e471c2ae-d402-45dd-8feb-6229aa347332',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(40,165,167,0.58)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'c55e76be-a1e2-42d2-b41a-a5e9e0167372',
            x: 8,
            y: 15,
            w: 4,
            h: 4
          },
          name: 'Exit seat',
          color: '#ffffff',
          bgcolor: 'rgba(40,84,167,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '2507852c-ba10-41bb-b913-707eff98278d',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(40,84,167,0.63)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'db3df296-feea-4b61-ba7a-5cef89650500',
            x: 8,
            y: 19,
            w: 4,
            h: 4
          },
          name: 'Lights',
          color: '#ffffff',
          bgcolor: 'rgba(40,84,167,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '87564921-44e8-4ffc-a38f-f59c305fb5d1',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(40,84,167,0.63)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'aa6ce516-44fe-40a8-8687-c8c199027204',
            x: 0,
            y: 15,
            w: 8,
            h: 4
          },
          name: 'Master Modes',
          color: '#ffffff',
          bgcolor: 'rgba(40,84,167,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '87ec3f2c-71ec-4e42-a015-69c5d4cd86d1',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(40,84,167,0.63)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'e4eecd65-401b-4322-87c4-78dc2f97a13d',
            x: 4,
            y: 28,
            w: 4,
            h: 4
          },
          name: 'Power +',
          color: '#ffffff',
          bgcolor: 'rgba(225,127,86,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'ef1e14b3-78eb-41c9-9f65-c8a95ad964cd',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(225,127,86,0.75)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'ac42320f-4041-4a48-acbf-f9236a6400a5',
            x: 8,
            y: 28,
            w: 4,
            h: 4
          },
          name: 'Power -',
          color: '#ffffff',
          bgcolor: 'rgba(225,127,86,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '1faec05f-96eb-4703-8490-917aee40eaf3',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(225,127,86,0.75)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '842e3d9f-6ea5-41e1-8bb3-b18f2ac1f0c6',
            x: 0,
            y: 36,
            w: 4,
            h: 4
          },
          name: 'Power Min',
          color: '#ffffff',
          bgcolor: 'rgba(225,127,86,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '24dff798-b280-406d-bb81-87d6af63c2b2',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(225,127,86,0.75)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '84073e64-fed8-4d58-a9ff-68d18c71a3ef',
            x: 0,
            y: 28,
            w: 4,
            h: 4
          },
          name: 'Power Max',
          color: '#ffffff',
          bgcolor: 'rgba(225,127,86,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '7ce0c54c-f602-4238-b190-757464bc1f23',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(225,127,86,0.75)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'e8e4d8db-16a8-4105-a158-fa4462ea574c',
            x: 0,
            y: 32,
            w: 4,
            h: 4
          },
          name: 'Engine +',
          color: '#ffffff',
          bgcolor: 'rgba(225,127,86,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'b6cbf8f8-dc02-4664-aa31-10c80384aaf6',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(225,127,86,0.75)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '01282397-3352-42b7-bc99-d763f11a74a4',
            x: 4,
            y: 32,
            w: 4,
            h: 4
          },
          name: 'Shield +',
          color: '#ffffff',
          bgcolor: 'rgba(225,127,86,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'c88d3914-2e24-408a-aad0-0ddb02f7053b',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(225,127,86,0.75)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '862143e1-debb-42c4-ad7e-4415fa2c30dd',
            x: 8,
            y: 32,
            w: 4,
            h: 4
          },
          name: 'Weapon +',
          color: '#ffffff',
          bgcolor: 'rgba(225,127,86,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'dfc76b65-592c-4e97-bed2-644149bdbd77',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(225,127,86,0.75)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'd1063924-cf94-4306-aa11-5dcc8bf17a95',
            x: 4,
            y: 36,
            w: 8,
            h: 4
          },
          name: 'Reset Power',
          color: '#ffffff',
          bgcolor: 'rgba(225,127,86,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'bf95ed8d-b967-4c6a-8cc9-cc16cddd60f5',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(225,127,86,0.75)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '356450ad-1dd0-4b98-8cff-4d7a4689f3a6',
            x: 0,
            y: 41,
            w: 3,
            h: 4
          },
          name: 'Scan',
          color: '#ffffff',
          bgcolor: 'rgba(6,155,86,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'aa760bcc-034a-4ab7-b94d-a380c03249ce',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(6,155,86,0.61)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '34bfe159-07ba-49e7-a648-edd29455e5f0',
            x: 3,
            y: 41,
            w: 3,
            h: 4
          },
          name: 'Ping',
          color: '#ffffff',
          bgcolor: 'rgba(6,155,86,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'afa60d8f-910e-42c7-97e3-8c75b5956258',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(6,155,86,0.61)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '4592e3d9-515e-4fdc-995f-2c4dfb5fdf52',
            x: 6,
            y: 41,
            w: 3,
            h: 4
          },
          name: 'Ping 5',
          color: '#ffffff',
          bgcolor: 'rgba(6,155,86,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '08c9019e-ade5-4fd7-ac09-ee8375feaf76',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(6,155,86,0.61)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '403b06da-d4bc-4e65-b727-36ee701c7ba9',
            x: 9,
            y: 41,
            w: 3,
            h: 4
          },
          name: 'Ping ∞',
          color: '#ffffff',
          bgcolor: 'rgba(6,155,86,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '2334e7d3-b500-455c-9ffb-2694ee4b2989',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(6,155,86,0.61)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'd6d944e4-ffbf-490e-8f67-d906e7b28f65',
            x: 8,
            y: 23,
            w: 4,
            h: 4
          },
          name: 'Ask Cargo',
          color: '#ffffff',
          bgcolor: 'rgba(40,84,167,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '53e398db-9022-4f65-afd6-8fc236df5ea7',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(40,84,167,0.63)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'd13d5db2-b819-4d34-8dea-b71492da0f19',
            x: 4,
            y: 19,
            w: 4,
            h: 4
          },
          name: 'Lock',
          color: '#ffffff',
          bgcolor: 'rgba(40,84,167,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '09e6e320-8a62-461d-ba21-f8c063021b24',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(40,84,167,0.63)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        }
      ],
      pageListConfig: {
        bgcolor: '#3134346e',
        bgimg: '',
        bgsize: '',
        bgpos: {
          x: 'center',
          y: 'center'
        },
        bgrepeat: 'no-repeat',
        margin: 0,
        padding: 0,
        justifyitems: 'space-between'
      },
      pageItemConfig: {
        color: '#8a494985',
        bgcolor: '#2e2c2c03',
        bgimg: '',
        bgsize: '',
        bgpos: {
          x: 'center',
          y: 'center'
        },
        bgrepeat: 'no-repeat',
        border: 0,
        borderRadius: 0,
        margin: 0,
        padding: 2,
        height: '38',
        width: '128',
        fontFamily: 'Arial',
        fontWeight: '',
        fontSize: '15',
        onclickbgcolor: '#8a494985',
        onclickcolor: '#f3efef',
        onclickborder: '#18171703',
        borderColor: '#2e2c2c03',
        justifyitems: 'center'
      }
    },
    {
      uid: '90475a75-d659-4c05-b5fb-af863024169b',
      name: 'Combat',
      pageConfig: {
        bgcolor: '#506173',
        bgimg: '2.png',
        bgsize: 'cover',
        bgpos: {
          x: 'center',
          y: 'center'
        },
        bgrepeat: 'no-repeat'
      },
      items: [
        {
          grid: {
            i: '0bff7ede-fe2b-4876-a8e6-857570c2e857',
            x: 0,
            y: 1,
            w: 6,
            h: 2
          },
          name: 'Attackers',
          color: 'rgba(212,20,20,1)',
          bgcolor: 'rgba(40,167,69,0.01)',
          type: 'img/text',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: '0',
          borderColor: '#F7F7F7',
          borderRadius: '0',
          action: '',
          fontFamily: 'Monospace',
          fontWeight: '800',
          fontSize: '17',
          onclickbgcolor: 'rgba(40, 167, 69, 0.59)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: false,
          resizeHandles: []
        },
        {
          grid: {
            i: 'f9c7a5e8-63a9-44b7-92ca-4ab8f8a9b812',
            x: 0,
            y: 3,
            w: 3,
            h: 5
          },
          name: 'Next',
          color: '#ffffff',
          bgcolor: 'rgba(167,40,42,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '6a526c03-6f38-4be1-97c8-8269accc049d',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(167,40,42,0.74)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'cfd81066-15b9-45f1-823e-ec1054a47daa',
            x: 3,
            y: 3,
            w: 3,
            h: 5
          },
          name: 'Near',
          color: '#ffffff',
          bgcolor: 'rgba(167,40,42,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '13e25e83-c8bb-4f91-a25f-3858121ea50a',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(167,40,42,0.74)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '9ef0531f-17df-4bcd-8e97-e067aec4d8a4',
            x: 6,
            y: 1,
            w: 6,
            h: 2
          },
          name: 'Hostiles',
          color: 'rgba(212,134,20,1)',
          bgcolor: 'rgba(40,167,69,0.01)',
          type: 'img/text',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: '0',
          borderColor: '#F7F7F7',
          borderRadius: '0',
          action: '',
          fontFamily: 'Monospace',
          fontWeight: '800',
          fontSize: '17',
          onclickbgcolor: 'rgba(40, 167, 69, 0.59)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: false,
          resizeHandles: []
        },
        {
          grid: {
            i: 'a653053f-649e-413b-8002-d579ad38b53b',
            x: 6,
            y: 3,
            w: 3,
            h: 5
          },
          name: 'Next',
          color: '#ffffff',
          bgcolor: 'rgba(212,134,20,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'f0336109-115e-44d0-926f-28616011f1a0',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(212,134,20,0.77)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '0de503e3-ebe1-4663-9231-a517b40bf4b4',
            x: 9,
            y: 3,
            w: 3,
            h: 5
          },
          name: 'Near',
          color: '#ffffff',
          bgcolor: 'rgba(212,134,20,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '33561cb0-f1a5-4a3d-9a06-bda738c94635',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(212,134,20,0.77)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'f801e251-4de7-4c71-88b6-a784bec33a36',
            x: 0,
            y: 9,
            w: 6,
            h: 2
          },
          name: 'Friendly',
          color: 'rgba(32,212,20,1)',
          bgcolor: 'rgba(40,167,69,0.01)',
          type: 'img/text',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: '0',
          borderColor: '#F7F7F7',
          borderRadius: '0',
          action: '',
          fontFamily: 'Monospace',
          fontWeight: '800',
          fontSize: '17',
          onclickbgcolor: 'rgba(40, 167, 69, 0.59)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: false,
          resizeHandles: []
        },
        {
          grid: {
            i: '9c8ab84d-08fd-4239-8a36-f5d6aedcf21d',
            x: 0,
            y: 11,
            w: 3,
            h: 5
          },
          name: 'Next',
          color: '#ffffff',
          bgcolor: 'rgba(32,212,20,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '54fc2c39-8b81-479e-9e83-21aaebc8775e',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(32,212,20,0.76)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '8255bd06-8510-4311-850c-bc9039687a2c',
            x: 3,
            y: 11,
            w: 3,
            h: 5
          },
          name: 'Near',
          color: '#ffffff',
          bgcolor: 'rgba(32,212,20,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'd56d01ec-15bb-477a-929b-d267207fc1f0',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(32,212,20,0.76)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'a5615e06-0949-467c-9d1b-19a84fd26e8c',
            x: 6,
            y: 9,
            w: 6,
            h: 2
          },
          name: 'All',
          color: 'rgba(206,206,206,1)',
          bgcolor: 'rgba(40,167,69,0.01)',
          type: 'img/text',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: '0',
          borderColor: '#F7F7F7',
          borderRadius: '0',
          action: '',
          fontFamily: 'Monospace',
          fontWeight: '800',
          fontSize: '17',
          onclickbgcolor: 'rgba(40, 167, 69, 0.59)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: false,
          resizeHandles: []
        },
        {
          grid: {
            i: '96af58a0-4cef-4d67-a787-3e06167bf091',
            x: 6,
            y: 11,
            w: 3,
            h: 5
          },
          name: 'Next',
          color: '#ffffff',
          bgcolor: 'rgba(206,206,206,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '9ea200df-4b11-4a45-bab5-bf040c88c775',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(206,206,206,0.75)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '8ecc6987-9230-4b1e-abcf-7a3065a16cf8',
            x: 9,
            y: 11,
            w: 3,
            h: 5
          },
          name: 'Near',
          color: '#ffffff',
          bgcolor: 'rgba(206,206,206,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '1809eb46-8777-46fe-b101-458fd9997bbe',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(206,206,206,0.75)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '31013f39-44ec-4b07-81a6-7b8ec68ee5ae',
            x: 0,
            y: 17,
            w: 12,
            h: 3
          },
          name: 'Pin',
          color: 'rgba(148,30,52,1)',
          bgcolor: 'rgba(40,167,69,0.01)',
          type: 'img/text',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: '0',
          borderColor: '#F7F7F7',
          borderRadius: '0',
          action: '',
          fontFamily: 'Monospace',
          fontWeight: '800',
          fontSize: '17',
          onclickbgcolor: 'rgba(40, 167, 69, 0.59)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: false,
          resizeHandles: []
        },
        {
          grid: {
            i: '6173abe9-8e56-44f9-9db1-b8f165ee4a39',
            x: 0,
            y: 20,
            w: 3,
            h: 5
          },
          name: '1',
          color: '#ffffff',
          bgcolor: 'rgba(148,30,52,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '094545d1-34e5-4938-b4a7-eb7a89fd9737',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(148,30,52,0.7)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '8c65a239-ac2c-4134-80e7-17ed2df72c8f',
            x: 3,
            y: 20,
            w: 3,
            h: 5
          },
          name: '2',
          color: '#ffffff',
          bgcolor: 'rgba(148,30,52,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '9c79caab-eaa0-49b0-b371-b6a7a83ba978',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(148,30,52,0.7)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '1300ae20-03a4-4ac4-90de-66fa66bcf532',
            x: 6,
            y: 20,
            w: 3,
            h: 5
          },
          name: '3',
          color: '#ffffff',
          bgcolor: 'rgba(148,30,52,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'a6c945f1-d1e0-4d33-82f0-14a51a7979d3',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(148,30,52,0.7)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '9d788333-9533-46a8-b6be-b6bef14014f6',
            x: 0,
            y: 25,
            w: 3,
            h: 4
          },
          name: 'Lock',
          color: '#ffffff',
          bgcolor: 'rgba(148,30,52,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '3e5cc013-352c-4d3d-b719-edddf1db6831',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(148,30,52,0.7)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '9a96d3ec-716b-4ae4-a2ed-71c5eed5defd',
            x: 3,
            y: 25,
            w: 3,
            h: 4
          },
          name: 'Lock',
          color: '#ffffff',
          bgcolor: 'rgba(148,30,52,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '647a7bd7-aa13-4ef3-b7d0-1e22ac751ef1',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(148,30,52,0.7)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'd37b06ed-1a3c-4bc1-8fc0-d950d76d4dd3',
            x: 6,
            y: 25,
            w: 3,
            h: 4
          },
          name: 'Lock',
          color: '#ffffff',
          bgcolor: 'rgba(148,30,52,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '9785767d-ce67-4011-af51-47a14698a6b7',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(148,30,52,0.7)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'c32a1977-095e-4565-87a1-edac857a21eb',
            x: 9,
            y: 20,
            w: 3,
            h: 9
          },
          name: 'Remove',
          color: '#ffffff',
          bgcolor: 'rgba(148,30,52,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'affff10a-60cc-44c0-b48a-01caa59c15ca',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(148,30,52,0.7)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'd5a67282-3ed2-4efa-8b9f-d1fd4cb97f09',
            x: 0,
            y: 31,
            w: 6,
            h: 4
          },
          name: 'Target in view',
          color: '#ffffff',
          bgcolor: 'rgba(40,160,167,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'eeebfe2a-2c7d-4aa7-b32b-652b0cac145b',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(40,160,167,0.8)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '4b73259a-b39a-4607-85d2-33ba7e0e3c0f',
            x: 6,
            y: 31,
            w: 6,
            h: 4
          },
          name: 'Auto target',
          color: '#ffffff',
          bgcolor: 'rgba(40,160,167,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '82ea1cda-2af6-4439-a35d-af178cc0d1a4',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(40,160,167,0.8)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'ed6c07a0-c4b2-431f-b3a7-c1a5af403944',
            x: 0,
            y: 35,
            w: 6,
            h: 5
          },
          name: 'Unlock target',
          color: '#ffffff',
          bgcolor: 'rgba(40,160,167,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'bdc08812-29c1-4ac1-adcb-f4c48a8a7583',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(40,160,167,0.8)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'e317d216-b48b-4aed-830d-f9b6107d22e8',
            x: 6,
            y: 35,
            w: 6,
            h: 5
          },
          name: 'Hail target',
          color: '#ffffff',
          bgcolor: 'rgba(40,160,167,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'ff7f7ca9-8b36-4f37-a508-b9a1d1623bfb',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(40,160,167,0.8)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        }
      ],
      pageListConfig: {
        bgcolor: '#3134346e',
        bgimg: '',
        bgsize: '',
        bgpos: {
          x: 'center',
          y: 'center'
        },
        bgrepeat: 'no-repeat',
        margin: 0,
        padding: 0,
        justifyitems: 'space-between'
      },
      pageItemConfig: {
        color: '#8a494985',
        bgcolor: '#2e2c2c03',
        bgimg: '',
        bgsize: '',
        bgpos: {
          x: 'center',
          y: 'center'
        },
        bgrepeat: 'no-repeat',
        border: 0,
        borderRadius: 0,
        margin: 0,
        padding: 2,
        height: '38',
        width: '128',
        fontFamily: 'Arial',
        fontWeight: '',
        fontSize: '15',
        onclickbgcolor: '#8a494985',
        onclickcolor: '#f3efef',
        onclickborder: '#18171703',
        borderColor: '#2e2c2c03',
        justifyitems: 'center'
      }
    },
    {
      uid: '596a82c9-b591-4b1e-8562-f8335e936ecf',
      name: 'Industrial',
      pageConfig: {
        bgcolor: '#506173',
        bgimg: '2.png',
        bgsize: 'cover',
        bgpos: {
          x: 'center',
          y: 'center'
        },
        bgrepeat: 'no-repeat'
      },
      items: [
        {
          grid: {
            i: 'ad11b6f8-6a30-4d4a-a078-b1295fd795d9',
            x: 0,
            y: 1,
            w: 12,
            h: 5
          },
          name: 'Mining / Savage',
          color: '#ffffff',
          bgcolor: 'rgba(167,87,40,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'dc4b59dd-4eec-4a41-9548-cd8abb901926',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(167,87,40,0.74)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'a4c7aa5c-0138-4012-b1b2-aedbb8836f7f',
            x: 0,
            y: 7,
            w: 3,
            h: 3
          },
          name: 'Modules',
          color: 'rgba(220,149,43,1)',
          bgcolor: 'rgba(167,135,40,0.01)',
          type: 'img/text',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: '0',
          borderColor: '#F7F7F7',
          borderRadius: '0',
          action: '',
          fontFamily: 'Monospace',
          fontWeight: '800',
          fontSize: '17',
          onclickbgcolor: 'rgba(40, 167, 69, 0.59)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: false,
          resizeHandles: []
        },
        {
          grid: {
            i: '6bba556c-1c65-4792-a1f5-1e5540f93329',
            x: 0,
            y: 10,
            w: 3,
            h: 5
          },
          name: '1',
          color: '#ffffff',
          bgcolor: 'rgba(220,149,43,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'a410e11c-4ce1-40df-85d9-2b1c06079650',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(220,149,43,0.75)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '1f8bc2e8-8b15-4373-853e-6a556f3108ab',
            x: 0,
            y: 15,
            w: 3,
            h: 5
          },
          name: '2',
          color: '#ffffff',
          bgcolor: 'rgba(220,149,43,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'dd6f9b17-8fe5-4040-89dd-7d618c42f2ec',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(220,149,43,0.75)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'c80974d8-3d82-4d4b-aba3-2d10be741bfe',
            x: 0,
            y: 20,
            w: 3,
            h: 5
          },
          name: '3',
          color: '#ffffff',
          bgcolor: 'rgba(220,149,43,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '881d2846-0aee-4c01-a95a-d8b5bbdedf11',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(220,149,43,0.75)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'a6358462-1b93-43b2-8c2d-6873ceea6e58',
            x: 4,
            y: 7,
            w: 8,
            h: 3
          },
          name: 'Salvage',
          color: 'rgba(220,149,43,1)',
          bgcolor: 'rgba(167,135,40,0.01)',
          type: 'img/text',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: '0',
          borderColor: '#F7F7F7',
          borderRadius: '0',
          action: '',
          fontFamily: 'Monospace',
          fontWeight: '800',
          fontSize: '17',
          onclickbgcolor: 'rgba(40, 167, 69, 0.59)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: false,
          resizeHandles: []
        },
        {
          grid: {
            i: '40dcef27-7f6d-40bd-b196-06d28fe8bcaf',
            x: 4,
            y: 15,
            w: 4,
            h: 5
          },
          name: 'Fracture',
          color: '#ffffff',
          bgcolor: 'rgba(220,149,43,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '0b5614be-9517-4597-9b89-778f8d9490b6',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(220,149,43,0.75)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '8de034b9-f6d9-4ad0-9aa1-c54d17e4327b',
            x: 8,
            y: 10,
            w: 4,
            h: 5
          },
          name: 'Fracture field',
          color: '#ffffff',
          bgcolor: 'rgba(220,149,43,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'a8ab604f-3675-4b09-ba28-8306b84d3d2f',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(220,149,43,0.75)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '41ce24e0-7582-4f61-ae88-f22faf61af9a',
            x: 4,
            y: 10,
            w: 4,
            h: 5
          },
          name: 'Disint field',
          color: '#ffffff',
          bgcolor: 'rgba(220,149,43,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '68be3b13-3967-4f14-9a0a-d6a74f05ad3a',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(220,149,43,0.75)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '7877bbdc-ef5c-4219-b579-556e3614845f',
            x: 8,
            y: 15,
            w: 4,
            h: 5
          },
          name: 'Focus all',
          color: '#ffffff',
          bgcolor: 'rgba(220,149,43,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'a3b3b90d-50df-45ab-8891-9b49327c57c2',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(220,149,43,0.75)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '1ab063a0-f623-4338-9e96-825dc02c7a81',
            x: 4,
            y: 20,
            w: 4,
            h: 5
          },
          name: 'Focus left',
          color: '#ffffff',
          bgcolor: 'rgba(220,149,43,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'b6f2937b-c450-4e21-a055-2d826bf3d14e',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(220,149,43,0.75)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '8d0e6db0-0b71-4232-bdab-ab94440f02e4',
            x: 8,
            y: 20,
            w: 4,
            h: 5
          },
          name: 'Focus right',
          color: '#ffffff',
          bgcolor: 'rgba(220,149,43,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: '6c86a5aa-f7ec-4c55-8c85-533b168d2fc8',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(220,149,43,0.75)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '5a13629a-002d-4620-adbf-3b2974148ba6',
            x: 0,
            y: 43,
            w: 12,
            h: 4
          },
          name: 'Jettison cargo',
          color: '#ffffff',
          bgcolor: 'rgba(176,28,30,1)',
          type: 'button',
          bgimg: '',
          bgsize: '',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: 1,
          borderColor: '#F7F7F7',
          borderRadius: 3,
          action: 'ea53c0f3-80de-46da-839b-2e4034e792b5',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(176,28,30,0.79)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: 'd38dbcce-7acd-4bba-b3f3-0735361fa957',
            x: 0,
            y: 25,
            w: 12,
            h: 12
          },
          name: '',
          color: '#ffffff',
          bgcolor: 'rgba(40,167,69,0.01)',
          type: 'img/text',
          bgimg: '',
          bgsize: 'contain',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: '0',
          borderColor: '#F7F7F7',
          borderRadius: '0',
          action: '',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(40, 167, 69, 0.59)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        },
        {
          grid: {
            i: '2555accb-797f-46b9-b636-b48c01a81db6',
            x: 0,
            y: 37,
            w: 12,
            h: 5
          },
          name: '',
          color: '#ffffff',
          bgcolor: 'rgba(40,167,69,0.01)',
          type: 'img/text',
          bgimg: '',
          bgsize: 'contain',
          bgpos: {
            x: 'center',
            y: 'center'
          },
          bgrepeat: 'no-repeat',
          border: '0',
          borderColor: '#F7F7F7',
          borderRadius: '0',
          action: '',
          fontFamily: 'Impact',
          fontWeight: '',
          fontSize: '17',
          onclickbgcolor: 'rgba(40, 167, 69, 0.59)',
          onclickcolor: '#FFFFFF',
          onclickbordercolor: '#FFFFFF',
          textShadow: true,
          boxShadow: true,
          resizeHandles: []
        }
      ],
      pageListConfig: {
        bgcolor: '#3134346e',
        bgimg: '',
        bgsize: '',
        bgpos: {
          x: 'center',
          y: 'center'
        },
        bgrepeat: 'no-repeat',
        margin: 0,
        padding: 0,
        justifyitems: 'space-between'
      },
      pageItemConfig: {
        color: '#8a494985',
        bgcolor: '#2e2c2c03',
        bgimg: '',
        bgsize: '',
        bgpos: {
          x: 'center',
          y: 'center'
        },
        bgrepeat: 'no-repeat',
        border: 0,
        borderRadius: 0,
        margin: 0,
        padding: 2,
        height: '38',
        width: '128',
        fontFamily: 'Arial',
        fontWeight: '',
        fontSize: '15',
        onclickbgcolor: '#8a494985',
        onclickcolor: '#f3efef',
        onclickborder: '#18171703',
        borderColor: '#2e2c2c03',
        justifyitems: 'center'
      }
    }
  ]
}
