import { KeyBindList, Modifier } from '../types/keybinds'

export const defaultSC40KeybindList: KeyBindList = {
  uid: 'sc4.0.defaultkb',
  name: 'StarCitizen4.0',
  keybinds: [
    {
      uid: '759a2dfb-1c93-47ff-8a03-51358b24a1b2',
      name: 'FlightReady',
      keybind: 'r',
      modifiers: [Modifier.RightAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 10,
      delayRepeat: 1000
    },
    {
      uid: 'b5f9706d-1eef-490f-a342-9a89eb0cd72d',
      name: 'Power',
      keybind: 'u',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '5cf3dbcc-176c-4fbe-b603-d43ff51c59b4',
      name: 'Engines',
      keybind: 'i',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '558c9d3f-9a65-48bd-aed4-d40ad39d25de',
      name: 'Shields',
      keybind: 'o',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'a0c006d5-b201-46d1-bf42-31ea26d94be9',
      name: 'Weapons',
      keybind: 'p',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'e471c2ae-d402-45dd-8feb-6229aa347332',
      name: 'Cruise',
      keybind: 'c',
      modifiers: [Modifier.LeftAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '1f5f0f4e-6ea2-4d11-a81e-a73f0e8d93ac',
      name: 'VTOL',
      keybind: 'k',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '792fb2e9-0bed-4d73-b671-09bd45bab358',
      name: 'Decoupled',
      keybind: 'c',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '9e4bbfe5-ff9a-4861-8a0c-dab53cff0113',
      name: 'Landing',
      keybind: 'n',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'f073a938-2aa0-461d-903c-394a94653971',
      name: 'Landing auto',
      keybind: 'n',
      modifiers: [],
      doubletap: false,
      hold: true,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '833ce51c-f7f9-4a8d-b162-198819161776',
      name: 'Request',
      keybind: 'n',
      modifiers: [Modifier.LeftAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'aa760bcc-034a-4ab7-b94d-a380c03249ce',
      name: 'Scan mode',
      keybind: 'v',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'afa60d8f-910e-42c7-97e3-8c75b5956258',
      name: 'Ping',
      keybind: 'Tab',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '08c9019e-ade5-4fd7-ac09-ee8375feaf76',
      name: 'Ping 5',
      keybind: 'Tab',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: true,
      repeatNumber: 5,
      delayRepeat: 3000
    },
    {
      uid: '2334e7d3-b500-455c-9ffb-2694ee4b2989',
      name: 'Ping infinite',
      keybind: 'Tab',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: true,
      repeatNumber: 'infinite',
      delayRepeat: 3000
    },
    {
      uid: 'b6cbf8f8-dc02-4664-aa31-10c80384aaf6',
      name: 'Engine +',
      keybind: 'F5',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'c88d3914-2e24-408a-aad0-0ddb02f7053b',
      name: 'Shiels +',
      keybind: 'F6',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'dfc76b65-592c-4e97-bed2-644149bdbd77',
      name: 'Weapon +',
      keybind: 'F7',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'bf95ed8d-b967-4c6a-8cc9-cc16cddd60f5',
      name: 'Reset power',
      keybind: 'F8',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '1faec05f-96eb-4703-8490-917aee40eaf3',
      name: 'Power -',
      keybind: 'F9',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '24dff798-b280-406d-bb81-87d6af63c2b2',
      name: 'Power Min',
      keybind: 'F9',
      modifiers: [],
      doubletap: true,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'ef1e14b3-78eb-41c9-9f65-c8a95ad964cd',
      name: 'Power +',
      keybind: 'F10',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '7ce0c54c-f602-4238-b190-757464bc1f23',
      name: 'Power Max',
      keybind: 'F10',
      modifiers: [],
      doubletap: true,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '3e5cc013-352c-4d3d-b719-edddf1db6831',
      name: 'Lock pin 1',
      keybind: '1',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '094545d1-34e5-4938-b4a7-eb7a89fd9737',
      name: 'Set Pin 1',
      keybind: '1',
      modifiers: [Modifier.LeftAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '647a7bd7-aa13-4ef3-b7d0-1e22ac751ef1',
      name: 'Lock Pin 2',
      keybind: '2',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '9c79caab-eaa0-49b0-b371-b6a7a83ba978',
      name: 'Set Pin 2',
      keybind: '2',
      modifiers: [Modifier.LeftAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '9785767d-ce67-4011-af51-47a14698a6b7',
      name: 'Lock Pin 3',
      keybind: '3',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'a6c945f1-d1e0-4d33-82f0-14a51a7979d3',
      name: 'Set Pin 3',
      keybind: '3',
      modifiers: [Modifier.LeftAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '6a526c03-6f38-4be1-97c8-8269accc049d',
      name: 'Next attacker',
      keybind: '4',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '13e25e83-c8bb-4f91-a25f-3858121ea50a',
      name: 'Near attacker',
      keybind: '4',
      modifiers: [Modifier.LeftAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'f0336109-115e-44d0-926f-28616011f1a0',
      name: 'Next hostile',
      keybind: '5',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '33561cb0-f1a5-4a3d-9a06-bda738c94635',
      name: 'Near hostile',
      keybind: '5',
      modifiers: [Modifier.LeftAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '54fc2c39-8b81-479e-9e83-21aaebc8775e',
      name: 'Next friendly',
      keybind: '6',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'd56d01ec-15bb-477a-929b-d267207fc1f0',
      name: 'Near friendly',
      keybind: '6',
      modifiers: [Modifier.LeftAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '9ea200df-4b11-4a45-bab5-bf040c88c775',
      name: 'Next all',
      keybind: '7',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '1809eb46-8777-46fe-b101-458fd9997bbe',
      name: 'Near all',
      keybind: '7',
      modifiers: [Modifier.LeftAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'ff7f7ca9-8b36-4f37-a508-b9a1d1623bfb',
      name: 'Hail target',
      keybind: '9',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'affff10a-60cc-44c0-b48a-01caa59c15ca',
      name: 'Remove all pin',
      keybind: '0',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'eeebfe2a-2c7d-4aa7-b32b-652b0cac145b',
      name: 'Target inView',
      keybind: 't',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '82ea1cda-2af6-4439-a35d-af178cc0d1a4',
      name: 'Auto target',
      keybind: 't',
      modifiers: [],
      doubletap: false,
      hold: true,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'bdc08812-29c1-4ac1-adcb-f4c48a8a7583',
      name: 'Unlock target',
      keybind: 't',
      modifiers: [Modifier.LeftAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '2507852c-ba10-41bb-b913-707eff98278d',
      name: 'Exit seat',
      keybind: 'y',
      modifiers: [],
      doubletap: false,
      hold: true,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '56edac2f-14fe-4ebb-9a04-d75647ba2097',
      name: 'Eject',
      keybind: 'y',
      modifiers: [Modifier.RightAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '87564921-44e8-4ffc-a38f-f59c305fb5d1',
      name: 'Lights',
      keybind: 'l',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '87ec3f2c-71ec-4e42-a015-69c5d4cd86d1',
      name: 'Master Mode',
      keybind: 'b',
      modifiers: [],
      doubletap: false,
      hold: true,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'dc4b59dd-4eec-4a41-9548-cd8abb901926',
      name: 'Mining/Salvage mode',
      keybind: 'm',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '0b5614be-9517-4597-9b89-778f8d9490b6',
      name: 'Fracture',
      keybind: 'w',
      modifiers: [Modifier.LeftAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '68be3b13-3967-4f14-9a0a-d6a74f05ad3a',
      name: 'Disint field',
      keybind: 'w',
      modifiers: [Modifier.RightAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'b6f2937b-c450-4e21-a055-2d826bf3d14e',
      name: 'Focus left',
      keybind: 'a',
      modifiers: [Modifier.LeftAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'a3b3b90d-50df-45ab-8891-9b49327c57c2',
      name: 'Focus all',
      keybind: 's',
      modifiers: [Modifier.LeftAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'a8ab604f-3675-4b09-ba28-8306b84d3d2f',
      name: 'Fracture field',
      keybind: 's',
      modifiers: [Modifier.RightAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '6c86a5aa-f7ec-4c55-8c85-533b168d2fc8',
      name: 'Focus right',
      keybind: 'd',
      modifiers: [Modifier.LeftAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'ea53c0f3-80de-46da-839b-2e4034e792b5',
      name: 'Jettison cargo',
      keybind: 'j',
      modifiers: [Modifier.LeftAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '53e398db-9022-4f65-afd6-8fc236df5ea7',
      name: 'Cargo request',
      keybind: 'n',
      modifiers: [Modifier.RightAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'a410e11c-4ce1-40df-85d9-2b1c06079650',
      name: 'Mining Mod 1',
      keybind: '1',
      modifiers: [Modifier.LeftAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'dd6f9b17-8fe5-4040-89dd-7d618c42f2ec',
      name: 'Mining Mod 2',
      keybind: '2',
      modifiers: [Modifier.LeftAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '881d2846-0aee-4c01-a95a-d8b5bbdedf11',
      name: 'Mining Mod 3',
      keybind: '3',
      modifiers: [Modifier.LeftAlt],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: 'd8404b75-fe5b-4833-b3c2-b97a1f534c6c',
      name: 'Toggle doors',
      keybind: ';',
      modifiers: [Modifier.RightShift],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    },
    {
      uid: '09e6e320-8a62-461d-ba21-f8c063021b24',
      name: 'Toggle lock doors',
      keybind: '\\',
      modifiers: [],
      doubletap: false,
      hold: false,
      repeat: false,
      repeatNumber: 1,
      delayRepeat: 0
    }
  ]
}
